#pragma config(Motor,  port1,           leftOne,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftTwo,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           vertical,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightOne,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightTwo,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	motor[leftOne] = 127;
	motor[rightOne] = 127 /** 0.4*/;
	motor[leftTwo] = 127;
	motor[rightTwo] = 127 /** 0.4*/;

	wait1Msec(3000);

	motor[leftOne] = 0;
	motor[rightOne] = 0 * 0.3;
	motor[leftTwo] = 0;
	motor[rightTwo] = 0 * 0.3;
	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
	while (true)
	{
		//Stuff
		int leftJoystick = vexRT[Ch3];
		motor[leftOne] = leftJoystick;
		motor[leftTwo] = leftJoystick;

		int rightJoystick = vexRT[Ch2] /** 0.3*/;
		motor[rightOne] = rightJoystick;
		motor[rightTwo] = rightJoystick;

		if(vexRT[Btn6U] == 1)
		{
			motor[vertical] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[vertical] = -127;
		}
		else
		{
			motor[vertical] = 0;
		}
		UserControlCodePlaceholderForTesting();
	}
}
